# Spot bare-metal AMD EPYC box on Rocky Linux 9 for exercising the
# AMD low-latency tuning playbook end to end.
#
#   terraform init && terraform apply
#   ../run-benchmark.sh
#   terraform destroy      # don't forget: ~$3/hr spot, ~$10/hr on-demand

locals {
  ssh_public_key  = file(pathexpand(var.ssh_public_key_path))
  ssh_private_key = pathexpand(var.ssh_private_key_path)
  my_ip_cidr      = "${chomp(data.http.my_ip.response_body)}/32"
  ssh_cidrs       = length(var.ssh_allowed_cidrs) > 0 ? var.ssh_allowed_cidrs : [local.my_ip_cidr]
  ami_id          = var.ami_id != "" ? var.ami_id : data.aws_ami.rocky9.id
  spot_max_price  = var.spot_max_price != "" ? var.spot_max_price : null

  tags = {
    Name    = var.name
    Project = "cpu-configuration"
    Purpose = "amd-epyc-low-latency-benchmark"
  }
}

data "http" "my_ip" {
  url = "https://checkip.amazonaws.com"
}

# Official Rocky Linux AMIs are published by the Rocky Enterprise Software Foundation.
data "aws_ami" "rocky9" {
  most_recent = true
  owners      = ["792107900819"]

  filter {
    name   = "name"
    values = ["Rocky-9-EC2-Base-*.x86_64"]
  }
  filter {
    name   = "architecture"
    values = ["x86_64"]
  }
  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

data "aws_vpc" "default" {
  default = true
}

data "aws_subnets" "default" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.default.id]
  }
  dynamic "filter" {
    for_each = var.availability_zone != "" ? [1] : []
    content {
      name   = "availability-zone"
      values = [var.availability_zone]
    }
  }
}

# --- IAM role + instance profile (SSM Session Manager as an SSH fallback) ---

data "aws_iam_policy_document" "ec2_trust" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "bench" {
  name               = "${var.name}-role"
  assume_role_policy = data.aws_iam_policy_document.ec2_trust.json
  tags               = local.tags
}

resource "aws_iam_role_policy_attachment" "ssm" {
  role       = aws_iam_role.bench.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}

resource "aws_iam_instance_profile" "bench" {
  name = "${var.name}-profile"
  role = aws_iam_role.bench.name
  tags = local.tags
}

# --- Network ---

resource "aws_key_pair" "bench" {
  key_name   = "${var.name}-key"
  public_key = local.ssh_public_key
  tags       = local.tags
}

resource "aws_security_group" "bench" {
  name        = "${var.name}-sg"
  description = "SSH for the AMD low-latency benchmark host"
  vpc_id      = data.aws_vpc.default.id
  tags        = local.tags

  ingress {
    description = "SSH"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = local.ssh_cidrs
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

# --- Instance ---

resource "aws_instance" "bench" {
  ami                         = local.ami_id
  instance_type               = var.instance_type
  subnet_id                   = data.aws_subnets.default.ids[0]
  vpc_security_group_ids      = [aws_security_group.bench.id]
  key_name                    = aws_key_pair.bench.key_name
  iam_instance_profile        = aws_iam_instance_profile.bench.name
  associate_public_ip_address = true
  ebs_optimized               = true

  dynamic "instance_market_options" {
    for_each = var.use_spot ? [1] : []
    content {
      market_type = "spot"
      spot_options {
        max_price                      = local.spot_max_price
        spot_instance_type             = "one-time"
        instance_interruption_behavior = "terminate"
      }
    }
  }

  root_block_device {
    volume_type           = "gp3"
    volume_size           = var.root_volume_gb
    delete_on_termination = true
    encrypted             = true
  }

  metadata_options {
    http_tokens                 = "required"
    http_put_response_hop_limit = 1
  }

  tags        = local.tags
  volume_tags = local.tags

  lifecycle {
    ignore_changes = [ami] # don't replace a running box because a newer Rocky AMI appeared
  }
}

# --- Ansible inventory ---

resource "local_file" "inventory" {
  filename        = "${path.module}/${var.inventory_path}"
  file_permission = "0644"
  content         = <<-EOT
    # Generated by terraform; do not edit. Group vars live in group_vars/bench.yml.
    [bench]
    ${aws_instance.bench.public_ip} ansible_user=rocky ansible_ssh_private_key_file=${local.ssh_private_key} ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  EOT
}
